### ISSUE TITLE
Use JSX

### ISSUE THREAD

**Issue by nkkollaw** [selaux/react-gtk#3]
Would it be possible to use JSX, and how..? :-)

**Comment by selaux** [comment]
Yes that should definitely be possible. I think it should be as easy as adapting the [webpack config](https://github.com/selaux/react-gtk/blob/master/example/webpack.config.js) to transpile `jsx` files to js.

**Comment by nkkollaw** [comment]
Very nice.
I'm just incompetent. I've always developed for the Web, and I have no idea how things work on the desktop.
If React is used, is used within Node instead of the browser, so React has access to any API Node has access to, correct?

**Comment by nkkollaw** [comment]
OK, I tried: https://github.com/nkkollaw/react-gtk/commit/bb66a02611811d705e3aae78f56fa1bfc656b7bd

Unfortunately it doesn't seem to be working. It looks as a scope problem, I'm getting "JS ERROR: TypeError: imports.gi is undefined".

I don't know if I am doing something wrong, or if the lib is not designed to use JSX.

**Comment by selaux** [comment]
This was indeed not as easy as I thought, because react only interprets lowercase components as native so `<GtkWindow>` wont work, but `gtk-window` will. I did some refactoring and now the example is written in jsx. [Take a look](https://github.com/selaux/react-gtk/commit/255a603bf28d081a120f91867d20a0b857fdcf53).

**Comment by nkkollaw** [comment]
Ohhh...

I don't understand why react-gtk would have to be a native component (not saying it shouldn't, just that I don't understand why), I guess one could keep the old naming by wrapping the lowercase components.

Awesome, man!

Are you still interested in the project? I'd love to help if there is a roadmap and I understand how the thing works/what I have to do.

**Comment by selaux** [comment]
The reason why it needs to be a native component is that we implement our own reconciler, so all gtk components are not really react components but are handled by the reconciler directly.

I'm still interested in bringing react to gtk, but this is a tremendous amount of work. There is no real roadmap as this was just an experiment I tried once to understand (and make use of) the new react fiber architecture. I am not entierly sure if all GTK concepts can even be represented in React.

If you are interested in learning how this works there are some useful links here: https://www.npmjs.com/package/react-reconciler

**Comment by selaux** [comment]
Regarding react-gtk most of the grunt work is implemented in [GtkWidget](https://github.com/selaux/react-gtk/blob/master/src/components/GtkWidget.js) and [the reconciler itself](https://github.com/selaux/react-gtk/blob/master/src/reconciler.js)

**Comment by nkkollaw** [comment]
I see.

I think React is a great tool for GTK apps. Developing GTK apps with the Builder seems pretty cumbersome as you have to recompile every time and it takes forever (well, it's normal but I'm not used to it).

Using React for GTK apps could mean that you could save yourself the pain of compiling everything at every change (if anything, by outputting HTML until the app is fully working).

I think that this repo could use a "HACKING" or "CONTRIBUTING" document which explained the implementation. I've read about the reconciler, but it would be extremely helpful for contributors to have instructions on how to port a widget, for instance.
